// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { Transaction } from "./Transaction";

export class CollectEvent {
  static encode(message: CollectEvent, writer: Writer): void {
    const tx = message.tx;
    if (tx !== null) {
      writer.uint32(10);
      writer.fork();
      Transaction.encode(tx, writer);
      writer.ldelim();
    }

    writer.uint32(18);
    writer.string(message.recipient);

    writer.uint32(26);
    writer.string(message.owner);

    writer.uint32(32);
    writer.int32(message.tickLower);

    writer.uint32(40);
    writer.int32(message.tickUpper);

    writer.uint32(50);
    writer.string(message.amount0);

    writer.uint32(58);
    writer.string(message.amount1);

    writer.uint32(66);
    writer.string(message.poolAddress);
  }

  static decode(reader: Reader, length: i32): CollectEvent {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CollectEvent();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.tx = Transaction.decode(reader, reader.uint32());
          break;

        case 2:
          message.recipient = reader.string();
          break;

        case 3:
          message.owner = reader.string();
          break;

        case 4:
          message.tickLower = reader.int32();
          break;

        case 5:
          message.tickUpper = reader.int32();
          break;

        case 6:
          message.amount0 = reader.string();
          break;

        case 7:
          message.amount1 = reader.string();
          break;

        case 8:
          message.poolAddress = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  tx: Transaction | null;
  recipient: string;
  owner: string;
  tickLower: i32;
  tickUpper: i32;
  amount0: string;
  amount1: string;
  poolAddress: string;

  constructor(
    tx: Transaction | null = null,
    recipient: string = "",
    owner: string = "",
    tickLower: i32 = 0,
    tickUpper: i32 = 0,
    amount0: string = "",
    amount1: string = "",
    poolAddress: string = ""
  ) {
    this.tx = tx;
    this.recipient = recipient;
    this.owner = owner;
    this.tickLower = tickLower;
    this.tickUpper = tickUpper;
    this.amount0 = amount0;
    this.amount1 = amount1;
    this.poolAddress = poolAddress;
  }
}
