// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { Transaction } from "./Transaction";

export class SwapEvent {
  static encode(message: SwapEvent, writer: Writer): void {
    const tx = message.tx;
    if (tx !== null) {
      writer.uint32(10);
      writer.fork();
      Transaction.encode(tx, writer);
      writer.ldelim();
    }

    writer.uint32(18);
    writer.string(message.sender);

    writer.uint32(26);
    writer.string(message.recipient);

    writer.uint32(34);
    writer.string(message.amount0);

    writer.uint32(42);
    writer.string(message.amount1);

    writer.uint32(50);
    writer.string(message.sqrtPriceX96);

    writer.uint32(58);
    writer.string(message.liquidity);

    writer.uint32(64);
    writer.int32(message.tick);

    writer.uint32(74);
    writer.string(message.poolAddress);
  }

  static decode(reader: Reader, length: i32): SwapEvent {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SwapEvent();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.tx = Transaction.decode(reader, reader.uint32());
          break;

        case 2:
          message.sender = reader.string();
          break;

        case 3:
          message.recipient = reader.string();
          break;

        case 4:
          message.amount0 = reader.string();
          break;

        case 5:
          message.amount1 = reader.string();
          break;

        case 6:
          message.sqrtPriceX96 = reader.string();
          break;

        case 7:
          message.liquidity = reader.string();
          break;

        case 8:
          message.tick = reader.int32();
          break;

        case 9:
          message.poolAddress = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  tx: Transaction | null;
  sender: string;
  recipient: string;
  amount0: string;
  amount1: string;
  sqrtPriceX96: string;
  liquidity: string;
  tick: i32;
  poolAddress: string;

  constructor(
    tx: Transaction | null = null,
    sender: string = "",
    recipient: string = "",
    amount0: string = "",
    amount1: string = "",
    sqrtPriceX96: string = "",
    liquidity: string = "",
    tick: i32 = 0,
    poolAddress: string = ""
  ) {
    this.tx = tx;
    this.sender = sender;
    this.recipient = recipient;
    this.amount0 = amount0;
    this.amount1 = amount1;
    this.sqrtPriceX96 = sqrtPriceX96;
    this.liquidity = liquidity;
    this.tick = tick;
    this.poolAddress = poolAddress;
  }
}
