// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class TokenInfo {
  static encode(message: TokenInfo, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.name);

    writer.uint32(18);
    writer.string(message.symbol);

    writer.uint32(24);
    writer.uint64(message.decimals);

    writer.uint32(32);
    writer.bool(message.inConverter);

    writer.uint32(42);
    writer.string(message.totalSupply);
  }

  static decode(reader: Reader, length: i32): TokenInfo {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new TokenInfo();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.name = reader.string();
          break;

        case 2:
          message.symbol = reader.string();
          break;

        case 3:
          message.decimals = reader.uint64();
          break;

        case 4:
          message.inConverter = reader.bool();
          break;

        case 5:
          message.totalSupply = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  name: string;
  symbol: string;
  decimals: u64;
  inConverter: bool;
  totalSupply: string;

  constructor(
    name: string = "",
    symbol: string = "",
    decimals: u64 = 0,
    inConverter: bool = false,
    totalSupply: string = ""
  ) {
    this.name = name;
    this.symbol = symbol;
    this.decimals = decimals;
    this.inConverter = inConverter;
    this.totalSupply = totalSupply;
  }
}
